### ISSUE TITLE
How to transpile file?

### ISSUE THREAD

**Issue by d9k** [basicer/lua2js#3]
(this repo is the mirror of bitbucket repo but there no issue tracker there)

How to actually transpile file with lua2js? Input `.lua` file, output `.js` file?

**Comment by d9k** [comment]
ok, I wrote custom script based on `test_spec.js` source, but I don't like the result)

```
var peg = require("pegjs");
var gen = require("escodegen");
var fs = require("fs");


var helpers = fs.readFileSync("helpers.js").toString();
var lang = fs.readFileSync("lua.pegjs").toString();
var parser = peg.buildParser(helpers + lang);
//var exec = require('child_process').exec;

function compile(lua_src) {
    var AST;
    try {
        AST = parser.parse(lua_src, {forceVar: true, decorateLuaObjects: true, luaCalls: true, luaOperators: true, encloseWithFunctions: false });
    } catch ( e ) {
        return JSON.stringify(e);
    }

    return gen.generate(AST);
}

var lua_code = fs.readFileSync('./lua-tests/hello.lua').toString();

console.log(compile(lua_code));
```

result:

```
{
    __lua.call(2, print, this, 'print', 'Hello World!');
    __lua.call(2, print, this, 'print', 'How are you?');
    i = 10;
    do {
        __lua.call(2, print, this, 'print', __lua.concat('hi ', i));
        i = __lua.oneValue(__lua.sub(i, 1));
    } while (!__lua.lt(i, 0));
}
```

**Comment by d9k** [comment]
I'm looking for lua-to-js transpiler which would produce more native js code, like the code produced by coffeescript compiler.
Is it possible?

**Comment by basicer** [comment]
In the object you pass to the parser, you can turn off some of the options like luaCalls and luaOperators which will change the the bits like `__lua.lt()` to `<`, remove __lua.call() and similar.   You will lose correct lua behavior in many cases however.
